name: linux64

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install build-essential libgl1-mesa-dev -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.3'
          modules: qtcharts qtwebengine

      - name: Build kleiner-brauhelfer-2
        run: |
          chmod +x ./build_linux64.sh
          chmod +x ./deployment/linux/64bit/deploy.sh
          chmod +x ./deployment/linux/64bit/AppImage/linuxdeployqt-6-x86_64.AppImage
          chmod +x ./deployment/linux/64bit/AppImage/AppRun
          ./build_linux64.sh "${Qt5_DIR}/bin/" 1
          mkdir -p deploy
          cp ./kbh2_*.deb deploy/
          cp ./kleiner-brauhelfer-2-x86_64.AppImage deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: kleiner-brauhelfer-2
          path: deploy
