name: linux64

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install build-essential mesa-common-dev libgl1-mesa-dev libfontconfig1 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5charts5* libqt5webengine* libqt5svg5* qtwebengine5-dev* libqt5webenginewidgets5 libqt5wayland* -y

      - name: Build kleiner-brauhelfer-2
        run: |
          chmod +x ./build_linux64.sh
          chmod +x ./deployment/linux/64bit/deploy.sh
          chmod +x ./deployment/linux/64bit/AppImage/linuxdeployqt-6-x86_64.AppImage
          chmod +x ./deployment/linux/64bit/AppImage/AppRun
          ./build_linux64.sh "/usr/lib/qt5/bin/" 1
          mkdir -p deploy
          cp ./kbh2_*.deb deploy/
          cp ./kleiner-brauhelfer-2-x86_64.AppImage deploy/

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: kleiner-brauhelfer-2
          path: deploy
